import React from 'react';
import AIAgentReportViewer from './AIAgentReportViewer';

// In your Reports component, update the state and handlers:
const [selectedReport, setSelectedReport] = useState(null);
const [isAIAgentViewerOpen, setIsAIAgentViewerOpen] = useState(false);

const handleViewReport = (report) => {
  setSelectedReport(report);
  if (report.source === 'ai_agent') {
    setIsAIAgentViewerOpen(true);
  } else {
    // Use regular report viewer for non-AI reports
    setIsReportViewerOpen(true);
  }
};

// Add the AI Agent Report Viewer to your return:
<AIAgentReportViewer 
  report={selectedReport}
  isOpen={isAIAgentViewerOpen}
  onClose={() => setIsAIAgentViewerOpen(false)}
  theme={theme}
/>
import { 
  FileText, Download, Printer, Share2, X, BarChart3, 
  TrendingUp, AlertTriangle, CheckCircle2, Lightbulb,
  Users, DollarSign, Package, Clock, Database, Brain,
  Zap, Target, LineChart, PieChart
} from 'lucide-react';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';

const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884D8', '#82ca9d'];

const AIAgentReportViewer = ({ report, isOpen, onClose, theme }) => {
  if (!isOpen || !report) return null;

  const isDark = theme === 'dark';
  const analysis = report.analysis;
  const llamaAnalysis = report.llamaAnalysis;

  const downloadReport = () => {
    const element = document.createElement("a");
    const file = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    element.href = URL.createObjectURL(file);
    element.download = `ai-report-${report.name}.json`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const exportPDF = () => {
    // This would generate a PDF in a real implementation
    alert('PDF export would be generated here in production');
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className={`${isDark ? 'bg-gray-800' : 'bg-white'} rounded-2xl w-full max-w-7xl max-h-[95vh] overflow-y-auto`}>
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700 sticky top-0 bg-inherit">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <div>
              <h3 className="text-xl font-bold">{report.name}</h3>
              <p className="text-sm text-gray-500">
                AI-Generated Report • {report.agentInfo.name} v{report.agentInfo.version}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={downloadReport}
              className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
              title="Download JSON"
            >
              <Download className="w-5 h-5" />
            </button>
            <button
              onClick={exportPDF}
              className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
              title="Export PDF"
            >
              <Printer className="w-5 h-5" />
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-6 space-y-8">
          {/* AI Agent Header */}
          <section className="bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 rounded-2xl p-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Brain className="w-8 h-8 text-purple-600" />
                <div>
                  <h4 className="text-lg font-bold">AI Agent Analysis Report</h4>
                  <p className="text-sm text-gray-600 dark:text-gray-300">
                    Generated by {report.agentInfo.name} • Analysis completed in {report.agentInfo.analysisDuration}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Zap className="w-5 h-5 text-yellow-500" />
                <span className="text-sm font-medium">Powered by LLaMA AI</span>
              </div>
            </div>
          </section>

          {/* Executive Summary from LLaMA */}
          {llamaAnalysis && (
            <section>
              <div className="flex items-center gap-3 mb-4">
                <FileText className="w-6 h-6 text-blue-600" />
                <h4 className="text-lg font-bold">AI Executive Summary</h4>
              </div>
              <div className={`${isDark ? 'bg-gray-700' : 'bg-white'} rounded-xl p-6 shadow-lg border-l-4 border-blue-500`}>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                  {llamaAnalysis.executive_summary || report.executiveSummary?.overview}
                </p>
              </div>
            </section>
          )}

          {/* Key Metrics Dashboard */}
          <section>
            <div className="flex items-center gap-3 mb-4">
              <BarChart3 className="w-6 h-6 text-green-600" />
              <h4 className="text-lg font-bold">Data Intelligence Dashboard</h4>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center border-l-4 border-blue-500">
                <Database className="w-8 h-8 text-blue-600 mx-auto mb-2" />
                <p className="text-2xl font-bold">{analysis.metadata.totalRows}</p>
                <p className="text-sm text-gray-500">Data Points</p>
              </div>
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center border-l-4 border-green-500">
                <TrendingUp className="w-8 h-8 text-green-600 mx-auto mb-2" />
                <p className="text-2xl font-bold">{analysis.insights.length}</p>
                <p className="text-sm text-gray-500">AI Insights</p>
              </div>
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center border-l-4 border-purple-500">
                <Target className="w-8 h-8 text-purple-600 mx-auto mb-2" />
                <p className="text-2xl font-bold">{analysis.recommendations.length}</p>
                <p className="text-sm text-gray-500">Recommendations</p>
              </div>
              <div className="bg-white dark:bg-gray-800 rounded-xl p-4 text-center border-l-4 border-orange-500">
                <Zap className="w-8 h-8 text-orange-600 mx-auto mb-2" />
                <p className="text-2xl font-bold">{analysis.patterns?.trends?.length || 0}</p>
                <p className="text-sm text-gray-500">Patterns Found</p>
              </div>
            </div>
          </section>

          {/* AI-Generated Insights */}
          <section>
            <div className="flex items-center gap-3 mb-4">
              <Lightbulb className="w-6 h-6 text-yellow-600" />
              <h4 className="text-lg font-bold">AI-Powered Insights</h4>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {analysis.insights.map((insight, index) => (
                <div
                  key={index}
                  className={`p-4 rounded-xl border-l-4 ${
                    insight.type === 'success' 
                      ? 'border-green-500 bg-green-50 dark:bg-green-900/20' 
                      : insight.type === 'warning'
                      ? 'border-orange-500 bg-orange-50 dark:bg-orange-900/20'
                      : 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    {insight.type === 'success' && <CheckCircle2 className="w-5 h-5 text-green-600 mt-0.5" />}
                    {insight.type === 'warning' && <AlertTriangle className="w-5 h-5 text-orange-600 mt-0.5" />}
                    {insight.type === 'info' && <TrendingUp className="w-5 h-5 text-blue-600 mt-0.5" />}
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <p className="font-semibold">{insight.title}</p>
                        <span className={`px-2 py-1 text-xs rounded-full ${
                          insight.impact === 'high' 
                            ? 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300'
                            : insight.impact === 'medium'
                            ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300'
                            : 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300'
                        }`}>
                          {insight.impact} impact
                        </span>
                      </div>
                      <p className="text-sm text-gray-600 dark:text-gray-300 mb-2">{insight.description}</p>
                      <div className="flex items-center justify-between text-xs text-gray-500">
                        <span>{insight.category}</span>
                        <span>Confidence: {insight.confidence}%</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Patterns and Trends */}
          {analysis.patterns && (
            <section>
              <div className="flex items-center gap-3 mb-4">
                <LineChart className="w-6 h-6 text-purple-600" />
                <h4 className="text-lg font-bold">Pattern Recognition</h4>
              </div>
              
              {/* Trends */}
              {analysis.patterns.trends.length > 0 && (
                <div className="mb-6">
                  <h5 className="font-semibold mb-3">Trend Analysis</h5>
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {analysis.patterns.trends.map((trend, index) => (
                      <div key={index} className={`${isDark ? 'bg-gray-700' : 'bg-white'} rounded-xl p-4 border-l-4 ${
                        trend.trend === 'increasing' ? 'border-green-500' : 'border-red-500'
                      }`}>
                        <p className="font-semibold text-sm mb-2">{trend.column}</p>
                        <div className="flex items-center gap-2">
                          <span className={`text-lg font-bold ${
                            trend.trend === 'increasing' ? 'text-green-600' : 'text-red-600'
                          }`}>
                            {trend.changePercentage > 0 ? '+' : ''}{trend.changePercentage}%
                          </span>
                          <TrendingUp className={`w-4 h-4 ${
                            trend.trend === 'increasing' ? 'text-green-600' : 'text-red-600 rotate-180'
                          }`} />
                        </div>
                        <p className="text-xs text-gray-500 mt-1">Confidence: {trend.confidence}%</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Correlations */}
              {analysis.patterns.correlations.length > 0 && (
                <div>
                  <h5 className="font-semibold mb-3">Relationship Analysis</h5>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {analysis.patterns.correlations.map((corr, index) => (
                      <div key={index} className={`${isDark ? 'bg-gray-700' : 'bg-white'} rounded-xl p-4 border-l-4 border-blue-500`}>
                        <p className="font-semibold text-sm mb-2">{corr.column1} ↔ {corr.column2}</p>
                        <div className="flex items-center gap-2 mb-2">
                          <span className="text-lg font-bold text-blue-600">r = {corr.correlation}</span>
                          <span className={`px-2 py-1 text-xs rounded-full ${
                            corr.strength === 'strong' 
                              ? 'bg-green-100 text-green-800 dark:bg-green-900/30'
                              : 'bg-blue-100 text-blue-800 dark:bg-blue-900/30'
                          }`}>
                            {corr.strength} {corr.direction} correlation
                          </span>
                        </div>
                        <p className="text-xs text-gray-500">
                          This suggests that as {corr.column1} changes, {corr.column2} tends to change in the {corr.direction} direction.
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </section>
          )}

          {/* Visualizations */}
          {analysis.visualizations.length > 0 && (
            <section>
              <div className="flex items-center gap-3 mb-4">
                <PieChart className="w-6 h-6 text-indigo-600" />
                <h4 className="text-lg font-bold">Data Visualizations</h4>
              </div>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {analysis.visualizations.map((viz, index) => (
                  <div key={index} className={`${isDark ? 'bg-gray-700' : 'bg-white'} rounded-xl p-6 shadow-lg`}>
                    <h5 className="font-semibold mb-4 text-center">{viz.title}</h5>
                    <ResponsiveContainer width="100%" height={300}>
                      {viz.type === 'histogram' ? (
                        <BarChart data={viz.data}>
                          <CartesianGrid strokeDasharray="3 3" opacity={0.1} />
                          <XAxis dataKey="range" />
                          <YAxis />
                          <Tooltip />
                          <Bar dataKey="count" fill={viz.config.fillColor} />
                        </BarChart>
                      ) : (
                        <LineChart data={viz.data}>
                          <CartesianGrid strokeDasharray="3 3" opacity={0.1} />
                          <XAxis dataKey="period" />
                          <YAxis />
                          <Tooltip />
                          <Line 
                            type="monotone" 
                            dataKey="value" 
                            stroke={viz.config.strokeColor} 
                            strokeWidth={2} 
                            dot={{ fill: viz.config.strokeColor, r: 4 }}
                          />
                        </LineChart>
                      )}
                    </ResponsiveContainer>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* AI Recommendations */}
          <section>
            <div className="flex items-center gap-3 mb-4">
              <Target className="w-6 h-6 text-red-600" />
              <h4 className="text-lg font-bold">AI Recommendations</h4>
            </div>
            <div className="space-y-4">
              {analysis.recommendations.map((rec, index) => (
                <div key={index} className={`p-4 rounded-xl border-l-4 ${
                  rec.priority === 'high' 
                    ? 'border-red-500 bg-red-50 dark:bg-red-900/20' 
                    : rec.priority === 'medium'
                    ? 'border-orange-500 bg-orange-50 dark:bg-orange-900/20'
                    : 'border-blue-500 bg-blue-50 dark:bg-blue-900/20'
                }`}>
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <span className={`px-2 py-1 text-xs font-semibold rounded-full ${
                          rec.priority === 'high'
                            ? 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300'
                            : rec.priority === 'medium'
                            ? 'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300'
                            : 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300'
                        }`}>
                          {rec.priority.toUpperCase()} PRIORITY
                        </span>
                        <span className="px-2 py-1 text-xs bg-gray-100 dark:bg-gray-700 rounded-full">
                          {rec.category}
                        </span>
                      </div>
                      <h5 className="font-semibold mb-2">{rec.title}</h5>
                      <p className="text-sm text-gray-600 dark:text-gray-300 mb-3">{rec.description}</p>
                      
                      <div className="mb-3">
                        <p className="text-sm font-semibold mb-1">Action Steps:</p>
                        <ul className="text-sm text-gray-600 dark:text-gray-300 space-y-1">
                          {rec.actionSteps.map((step, stepIndex) => (
                            <li key={stepIndex} className="flex items-start gap-2">
                              <div className="w-1 h-1 bg-gray-400 rounded-full mt-2 flex-shrink-0" />
                              {step}
                            </li>
                          ))}
                        </ul>
                      </div>

                      <div className="flex items-center gap-4 text-xs text-gray-500">
                        <span>Expected Impact: {rec.expectedImpact}</span>
                        <span>Implementation: {rec.implementationEffort}</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Predictive Insights */}
          {analysis.predictiveInsights.length > 0 && (
            <section>
              <div className="flex items-center gap-3 mb-4">
                <Zap className="w-6 h-6 text-yellow-600" />
                <h4 className="text-lg font-bold">Predictive Insights</h4>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {analysis.predictiveInsights.map((insight, index) => (
                  <div key={index} className={`${isDark ? 'bg-gray-700' : 'bg-white'} rounded-xl p-4 border-l-4 border-yellow-500`}>
                    <p className="font-semibold text-sm mb-2">{insight.metric}</p>
                    <p className="text-gray-600 dark:text-gray-300 mb-2">{insight.prediction}</p>
                    <div className="flex items-center justify-between text-xs text-gray-500">
                      <span>Basis: {insight.basis}</span>
                      <span>Confidence: {insight.confidence}%</span>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Technical Details */}
          <section>
            <div className="flex items-center gap-3 mb-4">
              <Database className="w-6 h-6 text-gray-600" />
              <h4 className="text-lg font-bold">Technical Analysis Details</h4>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Statistical Summary */}
              <div className={`${isDark ? 'bg-gray-700' : 'bg-white'} rounded-xl p-4`}>
                <h5 className="font-semibold mb-3">Statistical Summary</h5>
                <div className="space-y-2 text-sm">
                  {Object.entries(analysis.statisticalAnalysis).map(([column, stats]) => (
                    <div key={column} className="border-b border-gray-200 dark:border-gray-600 pb-2">
                      <p className="font-medium">{column}</p>
                      <div className="grid grid-cols-2 gap-1 text-xs text-gray-500">
                        <span>Mean: {stats.mean}</span>
                        <span>Std Dev: {stats.standardDeviation}</span>
                        <span>Min: {stats.min}</span>
                        <span>Max: {stats.max}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Data Quality */}
              <div className={`${isDark ? 'bg-gray-700' : 'bg-white'} rounded-xl p-4`}>
                <h5 className="font-semibold mb-3">Data Quality Assessment</h5>
                <div className="space-y-3">
                  {analysis.anomalies.map((anomaly, index) => (
                    <div key={index} className="flex items-start gap-2">
                      <AlertTriangle className={`w-4 h-4 mt-0.5 ${
                        anomaly.severity === 'high' ? 'text-red-500' : 
                        anomaly.severity === 'medium' ? 'text-orange-500' : 'text-yellow-500'
                      }`} />
                      <div>
                        <p className="text-sm font-medium">{anomaly.column}</p>
                        <p className="text-xs text-gray-500">{anomaly.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-200 dark:border-gray-700 bg-inherit">
          <div className="flex justify-between items-center">
            <div>
              <p className="text-sm text-gray-500">
                Generated by {report.agentInfo.name} v{report.agentInfo.version}
              </p>
              <p className="text-xs text-gray-400">
                Analysis completed: {new Date(report.timestamp).toLocaleString()}
              </p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={downloadReport}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                Export Report
              </button>
              <button
                onClick={onClose}
                className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIAgentReportViewer;